# Generated by Django 4.0 on 2021-12-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QianxuesenQianxuesenChengji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, max_length=200, null=True)),
                ('st_name', models.CharField(blank=True, max_length=200, null=True)),
                ('class_num', models.IntegerField(blank=True, null=True)),
                ('cl_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cl_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('cl_performance', models.CharField(blank=True, max_length=200, null=True)),
                ('cl_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cl_attribute', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'qianxuesen_qianxuesen_chengji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QianxuesenQianxuesenKebiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_school', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_cid', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_title', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_school', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('st_class', models.CharField(blank=True, max_length=500, null=True)),
                ('cl_credit', models.FloatField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_date', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_1', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_2', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_3', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_4', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_5', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_6', models.CharField(blank=True, max_length=100, null=True)),
                ('jieci_7', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'qianxuesen_qianxuesen_kebiao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QianxuesenQianxuesenProject19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, max_length=30, null=True)),
                ('st_name', models.CharField(blank=True, max_length=30, null=True)),
                ('st_school', models.CharField(blank=True, max_length=30, null=True)),
                ('st_major', models.CharField(blank=True, max_length=30, null=True)),
                ('major_2', models.CharField(blank=True, max_length=30, null=True)),
                ('st_class', models.CharField(blank=True, max_length=30, null=True)),
                ('st_grade', models.CharField(blank=True, max_length=30, null=True)),
                ('schoolyear', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_cid', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_credit', models.FloatField(blank=True, null=True)),
                ('cl_type', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_attribute', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_school', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_lanuage', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'qianxuesen_qianxuesen_project19',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QianxuesenQianxuesenQianxuesen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=20)),
                ('st_name', models.CharField(max_length=20)),
                ('st_school', models.CharField(max_length=20)),
                ('st_class', models.CharField(max_length=20)),
                ('cl_name', models.CharField(max_length=30)),
                ('cl_cid', models.CharField(max_length=30)),
                ('cl_credit', models.FloatField()),
                ('cl_id', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qianxuesen_qianxuesen_qianxuesen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QianxuesenQianxuesenQianxuesenst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, max_length=200, null=True)),
                ('st_major', models.CharField(blank=True, max_length=200, null=True)),
                ('major_2', models.CharField(blank=True, max_length=200, null=True)),
                ('st_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('st_name', models.CharField(blank=True, max_length=200, null=True)),
                ('st_class', models.CharField(blank=True, max_length=200, null=True)),
                ('st_school', models.CharField(blank=True, max_length=200, null=True)),
                ('total_credit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qianxuesen_qianxuesen_qianxuesenst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QxsTeaRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cl_name', models.CharField(max_length=30)),
                ('cl_cid', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=20)),
                ('point', models.IntegerField()),
                ('adv', models.CharField(blank=True, max_length=300, null=True)),
                ('st_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'qxs_tea_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QxsUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'qxs_users',
                'managed': False,
            },
        ),
    ]
